version: "3.8"

services:
  air:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app/
